In [3]:
import pandas as pd
import numpy as np
import streamlit as st


map_data = pd.DataFrame(
    np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4],
    columns=['lat', 'lon'])

st.map(map_data)

In [46]:
map_data.dtypes

lat    float64
lon    float64
dtype: object

portalbio_export_17-10-2019-13-06-22

In [121]:
class Texto():
    
    linhas = []
    __dock = []
    
    def __init__(self):
        file = open('Arquivos/portalbio_export_17-10-2019-13-06-22.csv', 'r')
        self.linhas = file.readlines()
    
    def construir(self, lines):
        self.__dock = [[item for item in itens.split(';')]for itens in lines]
        return self.__dock
    
txt = Texto()
lista = txt.construir(txt.linhas)
lista = pd.DataFrame(lista[:][1:], columns=lista[0][0:])
lista.rename(columns={'Latitude':'lat','Longitude':'lon'}, inplace=True)
mapa[['lat','lon']] = pd.DataFrame(lista[['lat','lon']]).astype(float)
lista.head()
#st.map(lista)
#mapa.head(20)
mapa.to_csv('Arquivos/mapa.csv')
lista.to_csv('Arquivos/mapa_biodiversidade.csv')

In [45]:
mapa.dtypes

lat    float64
lon    float64
dtype: object

In [47]:
class Texto():
    
    linhas = []
    __dock = []
    
    def __init__(self):
        file = open('Arquivos/portalbio_export_17-10-2019-13-06-22.csv', 'r')
        self.linhas = file.readlines()
    
    def construir(self, lines):
        self.__dock = [[item for item in itens.split(';')]for itens in lines]
        return self.__dock
    
txt = Texto()
lista = txt.construir(txt.linhas)

In [144]:
mapa01 = pd.read_csv('Arquivos/mapa.csv', header=0)
#mapa01.head()
mapa02 = mapa01[mapa01['lat'] == -23.195556]
mapa02.head(3)

     Unnamed: 0        lat        lon
397         397 -23.195556 -51.176389
398         398 -23.195556 -51.176389
403         403 -23.195556 -51.176389

In [120]:
st.deck_gl_chart(
    viewport={
         'latitude': 37.76,
         'longitude': -122.4,
         'zoom': 11,
         'pitch': 50,
     },
     layers=[{
         'type': 'HexagonLayer',
         'data': mapa01,
         'radius': 200,
         'elevationScale': 4,
         'elevationRange': [0, 1000],
         'pickable': True,
         'extruded': True,
     }, {
         'type': 'ScatterplotLayer',
         'data': mapa01,
     }])

In [122]:
def get_UN_data():
    AWS_BUCKET_URL = "https://streamlit-demo-data.s3-us-west-2.amazonaws.com"
    df = pd.read_csv(AWS_BUCKET_URL + "/agri.csv.gz")
    return df.set_index("Region")
df = get_UN_data()

In [124]:
df.head(10)

,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,...,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007
Region,,,,,,,,,,,,,,,,,,,,,
China,58340740.0,60690860.0,63942700.0,68462610.0,74747900.0,80445930.0,81718660.0,81474800.0,82195340.0,86542200.0,...,295117400.0,304490200.0,315511100.0,322771800.0,336394800.0,340623800.0,360834700.0,371939300.0,380320200.0,386448200.0
United States of America,89816580.0,90275010.0,93700380.0,94323650.0,97704050.0,97277180.0,101177900.0,103420600.0,104285200.0,102786400.0,...,167311700.0,170083400.0,173640200.0,170755800.0,167494400.0,172458200.0,183519100.0,181432900.0,176803000.0,184698800.0
India,50142680.0,50015760.0,51367730.0,52267720.0,49498330.0,49309560.0,52731470.0,55208160.0,56970870.0,60053830.0,...,137406600.0,143567200.0,142989200.0,147351100.0,137112300.0,151552000.0,149552600.0,156869200.0,164974800.0,175747700.0
USSR,72768810.0,73961920.0,70531000.0,81216890.0,80941960.0,90781310.0,92659220.0,98507460.0,93745540.0,100571500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Brazil,16564600.0,17344940.0,17443010.0,17658130.0,20367240.0,19238750.0,20650260.0,21256810.0,22008700.0,22533890.0,...,60706480.0,65353180.0,67416260.0,71250310.0,75603330.0,81198510.0,85626940.0,87363190.0,85319580.0,90075170.0
France,23408500.0,26654000.0,25202710.0,25321080.0,26780910.0,25447410.0,27156150.0,28165500.0,26664590.0,28293850.0,...,37902710.0,38125640.0,37449710.0,35782140.0,37868760.0,34763540.0,37570700.0,36169630.0,34776620.0,34377050.0
Germany,22077690.0,24241470.0,25340780.0,24843610.0,23988490.0,25236310.0,27208190.0,27321930.0,26233890.0,27169910.0,...,28969080.0,29794080.0,30055110.0,29948860.0,29032560.0,27700560.0,30391720.0,29285100.0,28460270.0,28778000.0
Italy,18638310.0,19289340.0,18918070.0,19893760.0,20564500.0,21158350.0,22352040.0,21546680.0,22380610.0,22301020.0,...,25574600.0,26866340.0,26136650.0,25580200.0,24916050.0,23984610.0,26710580.0,26063090.0,24948040.0,24706710.0
Argentina,11950390.0,12519320.0,13694660.0,12918230.0,12247380.0,13410430.0,14588430.0,13747960.0,14798930.0,14611240.0,...,25495380.0,26567310.0,26422920.0,26443270.0,25764360.0,27464940.0,27948600.0,30800780.0,30957870.0,33832140.0
Indonesia,7383684.0,8054871.0,7650931.0,8076970.0,7925503.0,8219212.0,7840406.0,9096512.0,9155070.0,9704501.0,...,26614870.0,26909240.0,27894050.0,28467300.0,30238130.0,32107000.0,34029230.0,35016270.0,36616890.0,38001410.0